extends:
  - airbnb-base

plugins:
  - angular

rules:
  import/no-extraneous-dependencies: off
  no-console: off
  max-len:
    - error
    - code: 120

env:
  browser: true
  jasmine: true
  angular/mocks: true
